export const projects = [
  {
    id: 1,
    title: 'celeratex',
    description: 'Celerate X',
    video: '/videos/celeratex-thumbnail.mp4',
  },
  {
    id: 2,
    title: 'phxkfc',
    description: 'Pizzahut x KFC',
    webp: '/images/phxkfc/webp/1.webp',
    jpg: '/images/phxkfc/jpg/1.jpg',
  },
  {
    id: 3,
    title: 'kfc',
    description: 'KFC',
    webp: '/images/kfc/webp/1.webp',
    jpg: '/images/kfc/jpg/1.jpg',
  },
  {
    id: 4,
    title: 'fob',
    description: 'Face of Blindness',
    webp: '/images/fob/webp/1.webp',
    jpg: '/images/fob/jpg/1.jpg',
  },
  {
    id: 5,
    title: 'asiamiles',
    description: 'Asia Miles',
    webp: '/images/asiamiles/webp/1.webp',
    jpg: '/images/asiamiles/jpg/1.jpg',
  },
  {
    id: 6,
    title: 'jfoodo',
    description: 'Jfoodo',
    webp: '/images/jfoodo/webp/4.webp',
    jpg: '/images/jfoodo/jpg/4.jpg',
  },
  {
    id: 7,
    title: 'huawei',
    description: 'Huawei',
    webp: '/images/huawei/webp/1.webp',
    jpg: '/images/huawei/jpg/1.jpg',
  },
  {
    id: 8,
    title: 'shangrila',
    description: 'Shangri-la',
    webp: '/images/shangrila/webp/1.webp',
    jpg: '/images/shangrila/jpg/1.jpg',
  },
  {
    id: 9,
    title: 'rakuten',
    description: 'Rakuten',
    webp: '/images/rakuten/webp/1.webp',
    jpg: '/images/rakuten/jpg/1.jpg',
  },
  {
    id: 10,
    title: 'scb',
    description: 'Standard Chartered',
    webp: '/images/scb/webp/0.webp',
    jpg: '/images/scb/jpg/0.jpg',
  },
]

export const projectsDetail = {
  celeratex: {
    headline: 'Celerate X',
    titles: ['React', 'Framer Motion', 'Tailwind CSS', 'Vite'],
    description: 'Celerate X',
    webp: ['/images/celeratex/webp/1.webp', '/images/celeratex/webp/3.webp'],
    jpg: ['/images/celeratex/jpg/1.jpg', '/images/celeratex/jpg/3.jpg'],
    colspan: ['col-span-2', 'col-span-2'],
  },

  phxkfc: {
    titles: ['JavaScript', 'GSAP', 'Phaser.js', 'Node.js', 'Socket.io'],
    headline: 'Pizza Hut X KFC',
    description:
      'Pizza Hut and KFC are releasing an epic collaboration pizza. Ogilvy Hong Kong created a co-op mobile video game: Pizza Hut x KFC Kitchen. The game connects two phones where you and a friend can make the latest Pizza Hut x KFC Chicken Popcorn Pizza unlock tasty rewards!',
    vimeo: 'https://player.vimeo.com/video/476169142?h=b7b1dd9b39',
    webp: [
      '/images/phxkfc/webp/1.webp',
      '/images/phxkfc/webp/2.webp',
      '/images/phxkfc/webp/3.webp',
      '/images/phxkfc/webp/4.webp',
      '/images/phxkfc/webp/5.webp',
      '/images/phxkfc/webp/6.webp',
      '/images/phxkfc/webp/7.webp',
      '/images/phxkfc/webp/8.webp',
    ],
    jpg: [
      '/images/phxkfc/jpg/1.jpg',
      '/images/phxkfc/jpg/2.jpg',
      '/images/phxkfc/jpg/3.jpg',
      '/images/phxkfc/jpg/4.jpg',
      '/images/phxkfc/jpg/5.jpg',
      '/images/phxkfc/jpg/6.jpg',
      '/images/phxkfc/jpg/7.jpg',
      '/images/phxkfc/jpg/8.jpg',
    ],
    colspan: [
      'col-span-2',
      'col-span-2 sm:col-span-1',
      'col-span-2 sm:col-span-1',
      'col-span-2',
      'col-span-2',
      'col-span-2 sm:col-span-1',
      'col-span-2 sm:col-span-1',
      'col-span-2',
    ],
  },

  kfc: {
    titles: ['JavaScript', 'GSAP', 'Phaser.js', 'Node.js', 'Socket.io'],
    headline: 'KFC',
    description: 'KFC Golden Fortune Bucket',
    vimeo: 'https://player.vimeo.com/video/243586805?h=0de9b8ffaf',
    webp: ['/images/kfc/webp/1.webp'],
    jpg: ['/images/kfc/jpg/1.jpg'],
    colspan: ['col-span-2'],
  },

  fob: {
    titles: ['JavaScript', 'GSAP', 'PHP', 'SCSS'],
    headline: 'Face of Blindness',
    description:
      'There are 285 million visually impaired people worldwide yet 80% of blindness can be treated or prevented. To raise funds for their global preventable blindness charity, Seeing is Believing, Standard Chartered sent 40 employees to climb Mount Kilimanjaro. We needed a digital fundraising idea which linked the Kilimanjaro fundraising climb with the phenomenon of preventable blindness and persuaded the public to make a measurable difference in the lives of blind people. And we needed it to be iconic, appealing, and shareable.',
    webp: [
      '/images/fob/webp/1.webp',
      '/images/fob/webp/2.webp',
      '/images/fob/webp/3.webp',
      '/images/fob/webp/4.webp',
      '/images/fob/webp/5.webp',
      '/images/fob/webp/6.webp',
      '/images/fob/webp/7.webp',
      '/images/fob/webp/8.webp',
      '/images/fob/webp/9.webp',
    ],
    jpg: [
      '/images/fob/jpg/1.jpg',
      '/images/fob/jpg/2.jpg',
      '/images/fob/jpg/3.jpg',
      '/images/fob/jpg/4.jpg',
      '/images/fob/jpg/5.jpg',
      '/images/fob/jpg/6.jpg',
      '/images/fob/jpg/7.jpg',
      '/images/fob/jpg/8.jpg',
      '/images/fob/jpg/9.jpg',
    ],
    colspan: [
      'col-span-2',
      'col-span-2 sm:col-span-1',
      'col-span-2 sm:col-span-1',
      'col-span-2',
      'col-span-2 sm:col-span-1',
      'col-span-2 sm:col-span-1',
      'col-span-2',
      'col-span-2',
      'col-span-2',
      'col-span-2',
      'col-span-2 sm:col-span-1',
      'col-span-2 sm:col-span-1',
    ],
  },

  asiamiles: {
    titles: ['React', 'JavaScript', 'GSAP', 'PHP', 'SCSS'],
    headline: 'Asia Miles',
    description: 'Asia Miles',
    webp: [
      '/images/asiamiles/webp/2.webp',
      '/images/asiamiles/webp/3.webp',
      '/images/asiamiles/webp/4.webp',
      '/images/asiamiles/webp/5.webp',
      '/images/asiamiles/webp/6.webp',
    ],
    jpg: [
      '/images/asiamiles/jpg/2.jpg',
      '/images/asiamiles/jpg/3.jpg',
      '/images/asiamiles/jpg/4.jpg',
      '/images/asiamiles/jpg/5.jpg',
      '/images/asiamiles/jpg/6.jpg',
    ],
    colspan: [
      'col-span-2',
      'col-span-2 w-fit justify-self-center',
      'col-span-2',
      'col-span-2 w-fit justify-self-center',
      'col-span-2',
    ],
  },

  jfoodo: {
    titles: ['JavaScript', 'GSAP', 'PHP', 'SCSS'],
    headline: 'Jfoodo',
    description:
      'A landing page for the Japan Food Product Overseas Promotion Center campaign in Hong Kong, geared towards promoting to the Hong Kong market 3 types of white fish from Japan – Yellowtail, Seabream, and Scallop. To make it more localised and interesting, the campaign also provided users with instructions and templates to fold their own fish origami ‘lucky charms’. During the wireframing stage, an idea was floated to feature a fortune-teller describing the benefits of eating specific seafood according to one’s Zodiac sign.',
    webp: [
      '/images/jfoodo/webp/1.webp',
      '/images/jfoodo/webp/2.webp',
      '/images/jfoodo/webp/3.webp',
    ],
    jpg: [
      '/images/jfoodo/jpg/1.jpg',
      '/images/jfoodo/jpg/2.jpg',
      '/images/jfoodo/jpg/3.jpg',
    ],
    colspan: ['col-span-2', 'col-span-2', 'col-span-2'],
  },

  huawei: {
    titles: ['JavaScript', 'GSAP', 'PHP', 'SCSS'],
    headline: 'Huawei Global Connectivity Index',
    description:
      'The Global Connectivity Index (GCI) is an annual study and white paper published by Huawei. It is a research platform that provides a comprehensive map of the global digital economy by measuring the digital transformation of 79 nations. The index was launched in 2014 and is in it’s 5th year of publication.',
    webp: [
      '/images/huawei/webp/2.webp',
      '/images/huawei/webp/3.webp',
      '/images/huawei/webp/4.webp',
      '/images/huawei/webp/5.webp',
      '/images/huawei/webp/6.webp',
      '/images/huawei/webp/8.webp',
    ],
    jpg: [
      '/images/huawei/jpg/2.jpg',
      '/images/huawei/jpg/3.jpg',
      '/images/huawei/jpg/4.jpg',
      '/images/huawei/jpg/5.jpg',
      '/images/huawei/jpg/6.jpg',
      '/images/huawei/jpg/8.jpg',
    ],
    colspan: [
      'col-span-2',
      'col-span-2 sm:col-span-1',
      'col-span-2 sm:col-span-1',
      'col-span-2',
      'col-span-2 sm:col-span-1',
      'col-span-2 sm:col-span-1',
      'col-span-2',
      'col-span-2',
      'col-span-2',
      'col-span-2',
      'col-span-2 sm:col-span-1',
      'col-span-2 sm:col-span-1',
    ],
  },

  shangrila: {
    titles: ['JavaScript', 'GSAP', 'PHP', 'SCSS'],
    headline: 'Shangri-La UGC gallery',
    description: 'Capture your special moment of Shangri-La',
    webp: [
      '/images/shangrila/webp/2.webp',
      '/images/shangrila/webp/3.webp',
      '/images/shangrila/webp/5.webp',
      '/images/shangrila/webp/6.webp',
      '/images/shangrila/webp/7.webp',
      '/images/shangrila/webp/8.webp',
      '/images/shangrila/webp/9.webp',
      '/images/shangrila/webp/10.webp',
      '/images/shangrila/webp/11.webp',
    ],
    jpg: [
      '/images/shangrila/jpg/2.jpg',
      '/images/shangrila/jpg/3.jpg',
      '/images/shangrila/jpg/5.jpg',
      '/images/shangrila/jpg/6.jpg',
      '/images/shangrila/jpg/7.jpg',
      '/images/shangrila/jpg/8.jpg',
      '/images/shangrila/jpg/9.jpg',
      '/images/shangrila/jpg/10.jpg',
      '/images/shangrila/jpg/11.jpg',
    ],
    colspan: [
      'col-span-2',
      'col-span-2',
      'col-span-2 sm:col-span-1',
      'col-span-2 sm:col-span-1',
      'col-span-2',
      'col-span-2',
      'col-span-2',
      'col-span-2',
      'col-span-2',
    ],
  },

  rakuten: {
    titles: ['JavaScript', 'GSAP', 'SCSS', 'PHP', 'Wordpress'],
    headline: 'Rakuten Today',
    description:
      'Rakuten.Today is the official corporate blog of Rakuten Group, Inc., one of the world’s leading internet services companies.',
    webp: ['/images/rakuten/webp/3.webp'],
    jpg: ['/images/rakuten/jpg/3.jpg'],
    colspan: ['col-span-2'],
  },

  scb: {
    titles: ['JavaScript', 'GSAP', 'SCSS', 'PHP', 'Wordpress'],
    headline: 'Standard Chartered International Graduate Program',
    description:
      'Standard Chartered Bank receives over 150k applications to their International Graduate Program every year. These are fresh graduates making their first major career decision and considering taking that next step of their lives with Standard Chartered.As such SCB wanted to revamp the website to better serve these graduates and to guide them through a difficult process. In particular, it needed to cater to people who have not had any experience in finance, and were seeking more knowledge about the industry, career path, and company they would like to work for.',
    webp: [
      '/images/scb/webp/1.webp',
      '/images/scb/webp/2.webp',
      '/images/scb/webp/3.webp',
      '/images/scb/webp/4.webp',
      '/images/scb/webp/5.webp',
      '/images/scb/webp/6.webp',
      '/images/scb/webp/7.webp',
      '/images/scb/webp/8.webp',
      '/images/scb/webp/9.webp',
    ],
    jpg: [
      '/images/scb/jpg/1.jpg',
      '/images/scb/jpg/2.jpg',
      '/images/scb/jpg/3.jpg',
      '/images/scb/jpg/4.jpg',
      '/images/scb/jpg/5.jpg',
      '/images/scb/jpg/6.jpg',
      '/images/scb/jpg/7.jpg',
      '/images/scb/jpg/8.jpg',
      '/images/scb/jpg/9.jpg',
    ],
    colspan: [
      'col-span-2',
      'col-span-2 sm:col-span-1',
      'col-span-2 sm:col-span-1',
      'col-span-2',
      'col-span-2 sm:col-span-1',
      'col-span-2 sm:col-span-1',
      'col-span-2',
      'col-span-2',
      'col-span-2',
      'col-span-2',
      'col-span-2 sm:col-span-1',
      'col-span-2 sm:col-span-1',
    ],
  },
}

export const experiences = [
  {
    id: 1,
    time: '2022 - Present',
    company: 'Ogilvy',
    title: 'Freelance Web Developer',
    tag: 'Freelance',
  },
  {
    id: 2,
    time: '2016 - 2022',
    company: 'Ogilvy',
    title: 'Web Developer',
    tag: 'Permanent',
  },
  {
    id: 3,
    time: '2014 - 2016',
    company: 'McCann',
    title: 'Programmer',
    tag: 'Permanent',
  },
]

export const clients = [
  {
    id: 1,
    name: 'Asia Miles',
    webp: '/images/brands/webp/asia-miles.webp',
    png: '/images/brands/png/asia-miles.jpg',
  },
  {
    id: 2,
    name: 'Cathay Pacific',
    webp: '/images/brands/webp/cathay-pacific.webp',
    png: '/images/brands/png/cathay-pacific.jpg',
  },
  {
    id: 3,
    name: 'Rakuten',
    webp: '/images/brands/webp/rakuten.webp',
    png: '/images/brands/png/rakuten.jpg',
  },
  {
    id: 4,
    name: 'Huawei',
    webp: '/images/brands/webp/huawei.webp',
    png: '/images/brands/png/huawei.jpg',
  },
  {
    id: 5,
    name: 'Pizza Hut',
    webp: '/images/brands/webp/pizza-hut.webp',
    png: '/images/brands/png/pizza-hut.jpg',
  },
  {
    id: 6,
    name: 'KFC',
    webp: '/images/brands/webp/kfc.webp',
    png: '/images/brands/png/kfc.jpg',
  },
  {
    id: 7,
    name: 'Shangri la',
    webp: '/images/brands/webp/shangri-la.webp',
    png: '/images/brands/png/shangri-la.jpg',
  },
  {
    id: 8,
    name: 'Celerate X',
    webp: '/images/brands/webp/celeratex.webp',
    png: '/images/brands/png/celeratex.jpg',
  },
  {
    id: 9,
    name: 'Jfoodo',
    webp: '/images/brands/webp/jfoodo.webp',
    png: '/images/brands/png/jfoodo.jpg',
  },
  {
    id: 10,
    name: 'Standard Chartered Bank',
    webp: '/images/brands/webp/standard-chartered.webp',
    png: '/images/brands/png/standard-chartered.jpg',
  },
]

export const profiles = [
  {
    id: 1,
    name: 'profile 1',
    webp: '/images/profile/webp/profile-1.webp',
    jpg: '/images/profile/jpg/profile-1.jpg',
  },
  {
    id: 2,
    name: 'profile 2',
    webp: '/images/profile/webp/profile-2.webp',
    jpg: '/images/profile/jpg/profile-2.jpg',
  },
]
